import { Data, IProductInput } from '@/types'
import { toSlug } from './utils'



export const products: IProductInput[] = [
  {
    name: "Nike Men's Slim-Fit Long-Sleeve T-shirt",
    slug: toSlug("Nike Men's Slim-Fit Long-Sleeve T-shirt"),
    category: 'Clothing',
    images: [
      'nike-mens-slimfit-longsleeve-1.jpg',
      'nike-mens-slimfit-longsleeve-2.jpg',
    ],
    brand: 'Nike',
    description:
      'Stay comfortable and stylish with this slim-fit long-sleeve tee.',
    price: 40,
    listPrice: 55,
    countInStock: 120,
    tags: ['new arrival'],
    colors: ['White', 'Red', 'Black'],
    sizes: ['S', 'M', 'L'],
    avgRating: 4.5,
    numReviews: 15,
    ratingDistribution: [
      { rating: 5, count: 10 },
      { rating: 4, count: 3 },
      { rating: 3, count: 2 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    numSales: 22,
    isPublished: true,
    reviews: [],
  },
  {
    name: "Adidas Women's Running Shoes Ultra-Boost",
    slug: toSlug("Adidas Women's Running Shoes Ultra-Boost"),
    category: 'Shoes',
    images: [
      'adidas-womens-ultraboost-1.jpg',
      'adidas-womens-ultraboost-2.jpg',
    ],
    brand: 'Adidas',
    description:
      'Lightweight running shoes with responsive cushioning for high-mileage comfort.',
    price: 120,
    listPrice: 150,
    countInStock: 50,
    tags: ['new arrival'],
    colors: ['White', 'Red', 'Black'],
    sizes: ['S', 'M', 'L'],
    avgRating: 4.7,
    numReviews: 22,
    ratingDistribution: [
      { rating: 5, count: 16 },
      { rating: 4, count: 4 },
      { rating: 3, count: 2 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    numSales: 35,
    isPublished: false,
    reviews: [],
  },
  {
    name: 'Puma Unisex Classic Suede Sneakers',
    slug: toSlug('Puma Unisex Classic Suede Sneakers'),
    category: 'Shoes',
    images: ['puma-classic-suede-1.jpg', 'puma-classic-suede-2.jpg'],
    brand: 'Puma',
    description:
      'Iconic suede sneakers for everyday wear, featuring timeless design.',
    price: 60,
    listPrice: 75,
    countInStock: 80,
    tags: ['new arrival'],
    colors: ['White', 'Red', 'Black'],
    sizes: ['S', 'M', 'L'],
    avgRating: 4.3,
    numReviews: 10,
    ratingDistribution: [
      { rating: 5, count: 5 },
      { rating: 4, count: 3 },
      { rating: 3, count: 2 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    numSales: 14,
    isPublished: true,
    reviews: [],
  },
  {
    name: "Under Armour Men's Storm Water-Resistant Hoodie",
    slug: toSlug("Under Armour Men's Storm Water-Resistant Hoodie"),
    category: 'Clothing',
    images: ['underarmour-hoodie-1.jpg', 'underarmour-hoodie-2.jpg'],
    brand: 'Under Armour',
    description: 'Water-repellent hoodie designed for workouts in light rain.',
    price: 70,
    listPrice: 85,
    countInStock: 55,
    tags: ['new arrival'],
    colors: ['White', 'Red', 'Black'],
    sizes: ['S', 'M', 'L'],
    avgRating: 4.1,
    numReviews: 8,
    ratingDistribution: [
      { rating: 5, count: 3 },
      { rating: 4, count: 3 },
      { rating: 3, count: 1 },
      { rating: 2, count: 1 },
      { rating: 1, count: 0 },
    ],
    numSales: 9,
    isPublished: false,
    reviews: [],
  },
  {
    name: "Reebok Women's High-Rise Leggings",
    slug: toSlug("Reebok Women's High-Rise Leggings"),
    category: 'Clothing',
    images: ['reebok-womens-leggings-1.jpg', 'reebok-womens-leggings-2.jpg'],
    brand: 'Reebok',
    description:
      'Flexible, high-rise leggings made with moisture-wicking fabric.',
    price: 35,
    listPrice: 45,
    countInStock: 100,
    tags: ['new arrival'],
    colors: ['White', 'Red', 'Black'],
    sizes: ['S', 'M', 'L'],
    avgRating: 4.6,
    numReviews: 14,
    ratingDistribution: [
      { rating: 5, count: 9 },
      { rating: 4, count: 4 },
      { rating: 3, count: 1 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    numSales: 21,
    isPublished: true,
    reviews: [],
  },
  {
    name: 'New Balance 574 Casual Sneakers',
    slug: toSlug('New Balance 574 Casual Sneakers'),
    category: 'Shoes',
    images: ['newbalance-574-1.jpg', 'newbalance-574-2.jpg'],
    brand: 'New Balance',
    description:
      'Classic 574 silhouette combining comfort, stability, and style.',
    price: 65,
    listPrice: 80,
    countInStock: 60,
    tags: ['new arrival'],
    colors: ['White', 'Red', 'Black'],
    sizes: ['S', 'M', 'L'],
    avgRating: 4.2,
    numReviews: 9,
    ratingDistribution: [
      { rating: 5, count: 4 },
      { rating: 4, count: 4 },
      { rating: 3, count: 1 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    numSales: 12,
    isPublished: false,
    reviews: [],
  },
  {
    name: 'Converse Chuck Taylor All Star High Tops',
    slug: toSlug('Converse Chuck Taylor All Star High Tops'),
    category: 'Shoes',
    images: ['converse-high-tops-1.jpg', 'converse-high-tops-2.jpg'],
    brand: 'Converse',
    description:
      'Timeless high-top silhouette with durable canvas construction.',
    price: 55,
    listPrice: 65,
    countInStock: 90,
    tags: ['new arrival'],
    colors: ['White', 'Red', 'Black'],
    sizes: ['S', 'M', 'L'],
    avgRating: 4.4,
    numReviews: 18,
    ratingDistribution: [
      { rating: 5, count: 11 },
      { rating: 4, count: 5 },
      { rating: 3, count: 2 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    numSales: 26,
    isPublished: true,
    reviews: [],
  },
  {
    name: "Columbia Women's Omni-Heat Jacket",
    slug: toSlug("Columbia Women's Omni-Heat Jacket"),
    category: 'Clothing',
    images: ['columbia-omni-heat-1.jpg', 'columbia-omni-heat-2.jpg'],
    brand: 'Columbia',
    description:
      'Thermal-reflective technology keeps you warm and protected outdoors.',
    price: 100,
    listPrice: 130,
    countInStock: 25,
    tags: ['new arrival'],
    colors: ['White', 'Red', 'Black'],
    sizes: ['S', 'M', 'L'],
    avgRating: 4.8,
    numReviews: 20,
    ratingDistribution: [
      { rating: 5, count: 15 },
      { rating: 4, count: 5 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    numSales: 28,
    isPublished: false,
    reviews: [],
  },
  {
    name: "Timberland Men's Premium 6-Inch Waterproof Boots",
    slug: toSlug("Timberland Men's Premium 6-Inch Waterproof Boots"),
    category: 'Shoes',
    images: ['timberland-premium-1.jpg', 'timberland-premium-2.jpg'],
    brand: 'Timberland',
    description: 'Iconic waterproof boots built for durability and traction.',
    price: 150,
    listPrice: 180,
    countInStock: 20,
    tags: ['new arrival'],
    colors: ['White', 'Red', 'Black'],
    sizes: ['S', 'M', 'L'],
    avgRating: 4.6,
    numReviews: 16,
    ratingDistribution: [
      { rating: 5, count: 10 },
      { rating: 4, count: 5 },
      { rating: 3, count: 1 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    numSales: 19,
    isPublished: true,
    reviews: [],
  },
  {
    name: "H&M Men's Skinny-Fit Stretch Jeans",
    slug: toSlug("H&M Men's Skinny-Fit Stretch Jeans"),
    category: 'Clothing',
    images: ['hm-mens-skinny-jeans-1.jpg', 'hm-mens-skinny-jeans-2.jpg'],
    brand: 'H&M',
    description: 'Modern skinny-fit jeans with comfortable stretch denim.',
    price: 30,
    listPrice: 40,
    countInStock: 70,
    tags: ['new arrival'],
    colors: ['White', 'Red', 'Black'],
    sizes: ['S', 'M', 'L'],
    avgRating: 4.0,
    numReviews: 8,
    ratingDistribution: [
      { rating: 5, count: 3 },
      { rating: 4, count: 3 },
      { rating: 3, count: 2 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    numSales: 14,
    isPublished: false,
    reviews: [],
  },
  {
    name: "Zara Women's Oversized Graphic T-Shirt",
    slug: toSlug("Zara Women's Oversized Graphic T-Shirt"),
    category: 'Clothing',
    images: ['zara-oversized-tee-1.jpg', 'zara-oversized-tee-2.jpg'],
    brand: 'Zara',
    description: 'Trendy, oversized cotton tee with a bold front print.',
    price: 25,
    listPrice: 35,
    countInStock: 50,
    tags: ['new arrival'],
    colors: ['White', 'Red', 'Black'],
    sizes: ['S', 'M', 'L'],
    avgRating: 4.3,
    numReviews: 10,
    ratingDistribution: [
      { rating: 5, count: 6 },
      { rating: 4, count: 3 },
      { rating: 3, count: 1 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    numSales: 15,
    isPublished: true,
    reviews: [],
  },
  {
    name: "Levi's Men's Trucker Denim Jacket",
    slug: toSlug("Levi's Men's Trucker Denim Jacket"),
    category: 'Clothing',
    images: ['levis-trucker-jacket-1.jpg', 'levis-trucker-jacket-2.jpg'],
    brand: "Levi's",
    description:
      'Classic denim trucker jacket offering vintage style and layering versatility.',
    price: 65,
    listPrice: 80,
    countInStock: 40,
    tags: ['new arrival'],
    colors: ['White', 'Red', 'Black'],
    sizes: ['S', 'M', 'L'],
    avgRating: 4.5,
    numReviews: 12,
    ratingDistribution: [
      { rating: 5, count: 7 },
      { rating: 4, count: 4 },
      { rating: 3, count: 1 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    numSales: 18,
    isPublished: false,
    reviews: [],
  },
  {
    name: "ASICS Men's Gel-Kayano 28 Stability Running Shoes",
    slug: toSlug("ASICS Men's Gel-Kayano 28 Stability Running Shoes"),
    category: 'Shoes',
    images: ['asics-gel-kayano-1.jpg', 'asics-gel-kayano-2.jpg'],
    brand: 'ASICS',
    description:
      'Premium stability running shoe for overpronators seeking structured support.',
    price: 130,
    listPrice: 160,
    countInStock: 25,
    tags: ['new arrival'],
    colors: ['White', 'Red', 'Black'],
    sizes: ['S', 'M', 'L'],
    avgRating: 4.7,
    numReviews: 17,
    ratingDistribution: [
      { rating: 5, count: 12 },
      { rating: 4, count: 4 },
      { rating: 3, count: 1 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    numSales: 24,
    isPublished: true,
    reviews: [],
  },
  {
    name: 'Crocs Classic Clogs Unisex',
    slug: toSlug('Crocs Classic Clogs Unisex'),
    category: 'Shoes',
    images: ['crocs-classic-1.jpg', 'crocs-classic-2.jpg'],
    brand: 'Crocs',
    description:
      'Lightweight, comfortable clogs for versatile indoor/outdoor use.',
    price: 35,
    listPrice: 45,
    countInStock: 100,
    tags: ['new arrival'],
    colors: ['White', 'Red', 'Black'],
    sizes: ['S', 'M', 'L'],
    avgRating: 3.9,
    numReviews: 7,
    ratingDistribution: [
      { rating: 5, count: 3 },
      { rating: 4, count: 2 },
      { rating: 3, count: 2 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    numSales: 10,
    isPublished: false,
    reviews: [],
  },
  {
    name: "Gap Women's Cozy Knit Pullover Sweater",
    slug: toSlug("Gap Women's Cozy Knit Pullover Sweater"),
    category: 'Clothing',
    images: ['gap-womens-sweater-1.jpg', 'gap-womens-sweater-2.jpg'],
    brand: 'Gap',
    description:
      'Soft knit sweater with a relaxed fit, ideal for cooler seasons.',
    price: 45,
    listPrice: 60,
    countInStock: 70,
    tags: ['new arrival'],
    colors: ['White', 'Red', 'Black'],
    sizes: ['S', 'M', 'L'],
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 5, count: 5 },
      { rating: 4, count: 4 },
      { rating: 3, count: 1 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    numSales: 13,
    isPublished: true,
    reviews: [],
  },
  {
    name: "Patagonia Men's Lightweight Down Vest",
    slug: toSlug("Patagonia Men's Lightweight Down Vest"),
    category: 'Clothing',
    images: ['patagonia-vest-1.jpg', 'patagonia-vest-2.jpg'],
    brand: 'Patagonia',
    description: 'Eco-friendly down vest that provides warmth without bulk.',
    price: 120,
    listPrice: 150,
    countInStock: 18,
    tags: ['new arrival'],
    colors: ['White', 'Red', 'Black'],
    sizes: ['S', 'M', 'L'],
    avgRating: 4.8,
    numReviews: 21,
    ratingDistribution: [
      { rating: 5, count: 16 },
      { rating: 4, count: 5 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    numSales: 29,
    isPublished: false,
    reviews: [],
  },
  {
    name: "Champion Men's Powerblend Fleece Joggers",
    slug: toSlug("Champion Men's Powerblend Fleece Joggers"),
    category: 'Clothing',
    images: ['champion-fleece-joggers-1.jpg', 'champion-fleece-joggers-2.jpg'],
    brand: 'Champion',
    description:
      'Soft fleece joggers offering comfort and durability in everyday wear.',
    price: 32,
    listPrice: 45,
    countInStock: 65,
    tags: ['new arrival'],
    colors: ['White', 'Red', 'Black'],
    sizes: ['S', 'M', 'L'],
    avgRating: 4.0,
    numReviews: 6,
    ratingDistribution: [
      { rating: 5, count: 2 },
      { rating: 4, count: 3 },
      { rating: 3, count: 1 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    numSales: 9,
    isPublished: true,
    reviews: [],
  },
  {
    name: 'Fossil Minimalist Leather Watch',
    slug: toSlug('Fossil Minimalist Leather Watch'),
    category: 'Accessories',
    images: ['fossil-minimalist-watch-1.jpg', 'fossil-minimalist-watch-2.jpg'],
    brand: 'Fossil',
    description: 'Sleek leather-strap watch with a minimalist dial design.',
    price: 90,
    listPrice: 110,
    countInStock: 30,
    tags: ['new arrival'],
    colors: ['White', 'Red', 'Black'],
    sizes: ['S', 'M', 'L'],
    avgRating: 4.3,
    numReviews: 8,
    ratingDistribution: [
      { rating: 5, count: 4 },
      { rating: 4, count: 3 },
      { rating: 3, count: 1 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    numSales: 11,
    isPublished: false,
    reviews: [],
  },
  {
    name: 'Ray-Ban Classic Wayfarer Sunglasses',
    slug: toSlug('Ray-Ban Classic Wayfarer Sunglasses'),
    category: 'Accessories',
    images: ['rayban-wayfarer-1.jpg', 'rayban-wayfarer-2.jpg'],
    brand: 'Ray-Ban',
    description: 'Timeless Wayfarer frames with 100% UV protection.',
    price: 130,
    listPrice: 160,
    countInStock: 20,
    tags: ['new arrival'],
    colors: ['White', 'Red', 'Black'],
    sizes: ['S', 'M', 'L'],
    avgRating: 4.6,
    numReviews: 14,
    ratingDistribution: [
      { rating: 5, count: 9 },
      { rating: 4, count: 4 },
      { rating: 3, count: 1 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    numSales: 16,
    isPublished: true,
    reviews: [],
  },
]

export const data: Data = {
  products,
  reviews: [],
  headerMenus: [
    {
      name: 'Todays Deals',
      href: '/deals',
    },
    {
      name: 'New Arrivals',
      href: '/registry',
    },
    {
      name: 'Featured Products',
      href: '/gift-cards', // Corrected
    },
    {
      name: 'Best Sellers',
      href: '/sell',
    },
    {
      name: 'Browsing History',
      href: '/history', // Changed to a more appropriate URL
    },
    {
      name: 'Customer Service',
      href: '/customer-service', // Changed to a meaningful path
    },
    {
      name: 'About us',
      href: '/about-us', // Corrected
    },
    {
      name: 'Help',
      href: '/help', // Corrected
    },
  ],
  carousels: [
    {
      title: 'Best Deal on Wrist watches',
      buttonCaption: 'Shop Now',
      url: '/search?category=Wrist Watch',
      image: '/images/banner1.jpg',
      isPublished: true,
    },
    {
      title: 'New Arrivals in T-shirts',
      buttonCaption: 'Explore',
      url: '/search?category=T-shirt',
      image: '/images/banner2.jpg',
      isPublished: true,
    },
    {
      title: 'Discover the Best Shoes',
      buttonCaption: 'Discover',
      url: '/search?category=shoes',
      image: '/images/banner3.jpg',
      isPublished: true,
    },
  ],
};


export default products
